GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/6a6e20af570efd165360118a

###

POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
    "content": "lol",
    "important": true
}

### 
PUT  http://localhost:3001/api/notes/6a6e5f0e426849cc926f1c3a
Content-Type: application/json

{
    "content": "lol",
    "important": false
}

